# Generated by Django 4.0.3 on 2022-09-02 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('no_of_rooms', models.IntegerField(default=0)),
                ('no_adult', models.IntegerField(default=0)),
                ('no_children', models.IntegerField(default=0)),
                ('booking_date', models.DateTimeField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('room_category', models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('DEL', 'DELUXE'), ('KIN', 'KING'), ('QUE', 'QUEEN')], max_length=3)),
                ('room_beds', models.IntegerField(default=0)),
                ('room_capacity', models.IntegerField()),
                ('room_rate', models.FloatField()),
                ('room_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(default=0)),
                ('p_amount', models.CharField(max_length=20)),
                ('p_card_no', models.CharField(max_length=20)),
                ('p_exp_date', models.DateTimeField()),
                ('g_cvv', models.IntegerField(max_length=3)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.IntegerField(default=0)),
                ('g_first_name', models.CharField(max_length=20)),
                ('g_last_name', models.CharField(max_length=20)),
                ('g_city', models.CharField(max_length=20)),
                ('g_state', models.CharField(max_length=20)),
                ('g_phnno', models.IntegerField(default=0)),
                ('g_email', models.CharField(max_length=20)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
