# Generated by Django 4.0.3 on 2022-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.CharField(max_length=30),
        ),
    ]
