# Generated by Django 4.0.3 on 2022-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_booking_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
