# Generated by Django 4.0.3 on 2022-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_due',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
